language: ruby
rvm:
  - 2.2.2
env:
  - CODE_CLIMATE_REPO_TOKEN=56d52e65eea7511997003934
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed RAILS_ENV=test --trace
  - bundle exec rake
